// Copies shared content from the website into the mobile app.
// The website is the source of truth: edit web/src/content/properties.ts and
// web/public/images, then run `node scripts/sync-content.mjs` from the repo root.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const webContent = path.join(root, "web/src/content/properties.ts");
const webImages = path.join(root, "web/public/images");
const mobileContent = path.join(root, "mobile/src/content");
const mobileImages = path.join(root, "mobile/assets/images");

fs.mkdirSync(mobileContent, { recursive: true });
fs.rmSync(mobileImages, { recursive: true, force: true });
fs.cpSync(webImages, mobileImages, { recursive: true });

const banner = "// GENERATED by scripts/sync-content.mjs — edit web/src/content/properties.ts instead.\n";
fs.writeFileSync(path.join(mobileContent, "properties.ts"), banner + fs.readFileSync(webContent, "utf8"));

const keys = [];
const walk = (dir, prefix = "") => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) walk(path.join(dir, entry.name), `${prefix}${entry.name}/`);
    else if (entry.name.endsWith(".jpg")) keys.push(`${prefix}${entry.name.replace(/\.jpg$/, "")}`);
  }
};
walk(mobileImages);
keys.sort();

// Metro needs static require() calls, so the map is written out explicitly.
fs.writeFileSync(
  path.join(mobileContent, "images.ts"),
  banner +
    "export const images: Record<string, number> = {\n" +
    keys.map((k) => `  "${k}": require("../../assets/images/${k}.jpg"),`).join("\n") +
    "\n};\n",
);

console.log(`Synced content and ${keys.length} images to mobile/.`);
