// GENERATED by scripts/sync-content.mjs — edit web/src/content/properties.ts instead.
export const images: Record<string, number> = {
  "rosewood-stadium/aerial": require("../../assets/images/rosewood-stadium/aerial.jpg"),
  "rosewood-stadium/aerial-wide": require("../../assets/images/rosewood-stadium/aerial-wide.jpg"),
  "rosewood-stadium/bedroom": require("../../assets/images/rosewood-stadium/bedroom.jpg"),
  "rosewood-stadium/bedroom-suite": require("../../assets/images/rosewood-stadium/bedroom-suite.jpg"),
  "rosewood-stadium/dining": require("../../assets/images/rosewood-stadium/dining.jpg"),
  "rosewood-stadium/kitchen": require("../../assets/images/rosewood-stadium/kitchen.jpg"),
  "rosewood-stadium/lounge": require("../../assets/images/rosewood-stadium/lounge.jpg"),
  "rosewood-stadium/plan-2br": require("../../assets/images/rosewood-stadium/plan-2br.jpg"),
  "rosewood-stadium/plan-3br": require("../../assets/images/rosewood-stadium/plan-3br.jpg"),
  "rosewood-stadium/tower-angle": require("../../assets/images/rosewood-stadium/tower-angle.jpg"),
  "rosewood-stadium/tower-front": require("../../assets/images/rosewood-stadium/tower-front.jpg"),
};
