// GENERATED by scripts/sync-content.mjs — edit web/src/content/properties.ts instead.
// Single source of truth for company + development content.
// The mobile app receives a copy of this file via `npm run sync` (see /scripts/sync-content.mjs).
// Keep it dependency-free: plain data and pure helpers only.

export type Area = "Stadium" | "Nyali" | "Kizingo" | "Nyali Beach";

export type UnitType = {
  id: string;
  name: string;
  bedrooms: number;
  bathrooms: number;
  sizeSqft: number;
  units: number;
  /** Image key, resolved per platform. */
  plan?: string;
  rooms: string[];
  /** Price bands by floor, in KES. */
  pricing: { floors: string; price: number }[];
};

export type TourScene = {
  id: string;
  title: string;
  /** Image key, resolved per platform. */
  image: string;
  /**
   * "360": a full equirectangular panorama (2:1), viewable all the way round and in a VR headset.
   * "wide": an ordinary still render, shown as a limited look-around until a 360 render replaces it.
   */
  kind: "360" | "wide";
};

export type Property = {
  slug: string;
  name: string;
  area: Area;
  status: "selling" | "coming-soon";
  tagline: string;
  summary: string;
  description: string[];
  address: string;
  coords: { lat: number; lng: number };
  /** True when the pin marks the neighbourhood rather than the surveyed plot. */
  coordsApproximate: boolean;
  floors?: number;
  totalUnits?: number;
  unitTypes: UnitType[];
  amenities: string[];
  nearby: { place: string; time: string }[];
  hero?: string;
  gallery: { image: string; caption: string }[];
  /** Rooms offered in the virtual tour, in walking order. */
  tour?: TourScene[];
  paymentPlan?: { label: string; percent: number; note: string }[];
  priceNote?: string;
};

export const company = {
  name: "Three Star Towers Limited",
  shortName: "Three Star Towers",
  strapline: "Premium property development in Mombasa",
  office: "Makadara, Mombasa",
  poBox: "P.O. Box 86499 – 80100, Mombasa",
  phones: ["+254 724 446 444", "+254 735 577 455"],
  whatsapp: "254724446444",
  emails: ["sales@heimatconsult.co.ke", "info@heimatconsult.co.ke"],
  website: "threestartowers.vercel.app",
  salesOffice: "BP Plaza (1st floor), Umoja Rd, Nyali, Mombasa",
  partners: [
    { role: "Developer", name: "Three Star Towers Limited" },
    { role: "Project management", name: "Heimat Consult Ltd" },
    { role: "Contractor", name: "Spearlead Construction Limited" },
  ],
};

const comingSoon = (area: string) => [
  `Rosewood is coming to ${area}. Floor plans, unit mix and pricing for this residence are being finalised.`,
  "Register your interest and our sales team will share details with you first.",
];

export const properties: Property[] = [
  {
    slug: "rosewood-stadium",
    name: "Rosewood Residence Stadium",
    area: "Stadium",
    status: "selling",
    tagline: "Where everyday moments transcend into extraordinary experiences.",
    summary:
      "45 premium two- and three-bedroom apartments across 15 floors, minutes from Mombasa CBD.",
    description: [
      "Rosewood Residence Stadium offers 45 premium units across 15 floors. Each home features a modern layout, abundant natural light and high-quality finishes, ensuring both comfort and style.",
      "Experience an exceptional lifestyle in a secure, well-designed community — perfect for families, professionals and anyone seeking modern living.",
    ],
    address: "Luhar Wadha St, Stadium Area, Mombasa",
    coords: { lat: -4.0449, lng: 39.6627 },
    coordsApproximate: true,
    floors: 15,
    totalUnits: 45,
    unitTypes: [
      {
        id: "2br",
        name: "2 Bedroom",
        bedrooms: 2,
        bathrooms: 2,
        sizeSqft: 1250,
        units: 30,
        plan: "rosewood-stadium/plan-2br",
        rooms: [
          "Living room",
          "Balcony",
          "Dining",
          "Kitchen",
          "Utility",
          "Lobby",
          "Bath",
          "Bedroom 1",
          "Master bedroom",
          "Master bath",
          "Master balcony",
        ],
        pricing: [
          { floors: "1st – 5th floor", price: 6_500_000 },
          { floors: "6th – 10th floor", price: 7_000_000 },
          { floors: "11th – 15th floor", price: 7_500_000 },
        ],
      },
      {
        id: "3br",
        name: "3 Bedroom",
        bedrooms: 3,
        bathrooms: 3,
        sizeSqft: 1950,
        units: 15,
        plan: "rosewood-stadium/plan-3br",
        rooms: [
          "Entrance room",
          "Cloak room",
          "Dining",
          "Living room",
          "Balcony",
          "Master bedroom",
          "Master balcony",
          "Master bath",
          "Bedroom 2",
          "Bath 2",
          "Bedroom 3",
          "Bath 3",
          "Utility",
          "Pantry",
          "Kitchen",
        ],
        pricing: [
          { floors: "1st – 5th floor", price: 10_000_000 },
          { floors: "6th – 10th floor", price: 10_500_000 },
          { floors: "11th – 15th floor", price: 11_000_000 },
        ],
      },
    ],
    amenities: [
      "High-speed elevators",
      "Multi-level parking",
      "Automatic power backup",
      "CCTV surveillance",
      "Borehole on-site",
      "Electric fence boundary",
      "Balconies and bay windows",
      "Granite kitchen countertops",
      "Built-in wardrobes",
      "Internet connectivity",
      "Bio digester",
    ],
    nearby: [
      { place: "Mary Immaculate Hospital", time: "2 min walk" },
      { place: "Technical University of Mombasa", time: "5 min walk" },
      { place: "Mombasa CBD", time: "10 min drive" },
      { place: "Moi International Airport", time: "15 min drive" },
      { place: "SGR – Mombasa Terminus", time: "20 min drive" },
      { place: "Mosques, schools and madrasas", time: "Walking distance" },
    ],
    hero: "rosewood-stadium/tower-front",
    gallery: [
      { image: "rosewood-stadium/tower-front", caption: "Front elevation" },
      { image: "rosewood-stadium/tower-angle", caption: "Street view at dusk" },
      { image: "rosewood-stadium/aerial", caption: "Aerial view" },
      { image: "rosewood-stadium/lounge", caption: "Lounge" },
      { image: "rosewood-stadium/dining", caption: "Dining" },
      { image: "rosewood-stadium/kitchen", caption: "Kitchen" },
      { image: "rosewood-stadium/bedroom", caption: "Master bedroom" },
      { image: "rosewood-stadium/bedroom-suite", caption: "Master suite" },
      { image: "rosewood-stadium/aerial-wide", caption: "The neighbourhood" },
    ],
    tour: [
      { id: "lounge", title: "Lounge", image: "rosewood-stadium/lounge", kind: "wide" },
      { id: "dining", title: "Dining", image: "rosewood-stadium/dining", kind: "wide" },
      { id: "kitchen", title: "Kitchen", image: "rosewood-stadium/kitchen", kind: "wide" },
      { id: "bedroom", title: "Master bedroom", image: "rosewood-stadium/bedroom", kind: "wide" },
    ],
    paymentPlan: [
      { label: "Deposit", percent: 30, note: "On booking" },
      { label: "Balance", percent: 60, note: "Spread over the 24-month construction period" },
      { label: "Handover", percent: 10, note: "On completion" },
    ],
    priceNote:
      "Prices from the published KES price list. Confirm current pricing and availability with sales. Terms & conditions apply.",
  },
  {
    slug: "rosewood-nyali",
    name: "Rosewood Residence Nyali",
    area: "Nyali",
    status: "coming-soon",
    tagline: "Leafy avenues, coastal calm.",
    summary: "A Rosewood address in Mombasa's most established residential suburb.",
    description: comingSoon("Nyali"),
    address: "Nyali, Mombasa",
    coords: { lat: -4.0331, lng: 39.7013 },
    coordsApproximate: true,
    unitTypes: [],
    amenities: [],
    nearby: [],
    gallery: [],
  },
  {
    slug: "rosewood-kizingo",
    name: "Rosewood Residence Kizingo",
    area: "Kizingo",
    status: "coming-soon",
    tagline: "Island living by the ocean drive.",
    summary: "A Rosewood address on Mombasa Island's quiet southern tip.",
    description: comingSoon("Kizingo"),
    address: "Kizingo, Mombasa Island",
    coords: { lat: -4.0684, lng: 39.6787 },
    coordsApproximate: true,
    unitTypes: [],
    amenities: [],
    nearby: [],
    gallery: [],
  },
  {
    slug: "rosewood-nyali-beach",
    name: "Rosewood Residence Nyali Beach",
    area: "Nyali Beach",
    status: "coming-soon",
    tagline: "Steps from the Indian Ocean.",
    summary: "A Rosewood address along the Nyali beachfront.",
    description: comingSoon("the Nyali beachfront"),
    address: "Nyali Beach, Mombasa",
    coords: { lat: -4.0432, lng: 39.7155 },
    coordsApproximate: true,
    unitTypes: [],
    amenities: [],
    nearby: [],
    gallery: [],
  },
];

export const getProperty = (slug: string) => properties.find((p) => p.slug === slug);

export const fromPrice = (p: Property): number | undefined => {
  const all = p.unitTypes.flatMap((u) => u.pricing.map((b) => b.price));
  return all.length ? Math.min(...all) : undefined;
};

export const formatKes = (n: number) => `KES ${n.toLocaleString("en-KE")}`;

export const formatKesShort = (n: number) => {
  const m = n / 1_000_000;
  return `KES ${Number.isInteger(m) ? m : m.toFixed(1)}M`;
};

export const sqftToSqm = (sqft: number) => Math.round(sqft * 0.092903);

export const whatsappLink = (message: string) =>
  `https://wa.me/${company.whatsapp}?text=${encodeURIComponent(message)}`;

export const directionsLink = (p: Property) =>
  `https://www.google.com/maps/dir/?api=1&destination=${p.coords.lat},${p.coords.lng}`;
